/// <reference types="emscripten" />
export { o as Change, u as DataCaptureComponent, t as DataCaptureComponentJSON, B as DataCaptureContext, x as DataCaptureContextCreationOptions, y as DataCaptureContextJSON, p as DataCaptureMode, r as DataCaptureModeJSON, P as PrivateChangeSet, s as PrivateDataCaptureComponent, w as PrivateDataCaptureContext, v as PrivateDataCaptureContextOptions, q as PrivateDataCaptureMode, A as PrivateFrameHandler, z as PrivateFrameHandlerResponse } from './Camera-C_4xOv5n.js';
import './Common.js';
import './DataCaptureContextSettings.js';
import './license/OpenSourceSoftwareLicenseInfo.js';
import './private/HtmlElementState.js';
import './private/Serializable.js';
import './private/nativeHandle.js';
import './tsHelper.js';
import './private/FrameReaders/WatermarkStack.js';
import './ScanditIcon.js';
import './private/utils/ScanditHTMLElement.js';
import './DataCaptureViewPlusRelated.js';
import './NotificationPresenter/NotificationPresenter.js';
import './NotificationPresenter/NotificationConfiguration.js';
import './NotificationPresenter/NotificationStyle.js';
import './ViewControls.js';
import './private/CustomLocationsView.js';
import './private/View.js';
import './private/AnchorPositions.js';
import './worker/OverrideState.js';
import './logger.js';
import './LoadingStatus.js';
